### PR TITLE
Comfort improvements.

### PR DESCRIPTION
**Pull request by martonmiklos**
Added Ctrl+O Ctrl+S Ctrl+N shortcuts. 
Added rememebering to the open, save, executable, etc. paths.
To keep the saving of the properties simple added the QCoreApplication::setApplicationName/version in the main.cpp.

### CODE REVIEW

**Comment by pedromateo** [comment]
Many thanks Miklós! I will merge these changes asap.
By the way, I was thinking to add Right Ctrl shortcut (e.g., as in VirtualBox) bound to PAUSE action. So, it would be easy to pause while test case execution.
What do you think about that? I think it would really improve user experience.

**Comment by pedromateo** [comment]
Moreover, sorry for the code. It is too old (I started doing this 7 years ago) and I am rewritting it little by little. Feel free to change whatever you want. I will try to review it and incorporate the changes asap.
Thanks

**Comment by martonmiklos** [comment]
Never worry about the code! You have shared it I have found it useful, so I have contributed.
This is how it rolls. 

Just a quick question: what is the purpose of the underscore characters in the variable names?
Somewhere I have seen the private variables prefixed somewhere suffixed with _. 
Is this the notation of the private members?

**Comment by pedromateo** [comment]
yes, underscore is for private stuff.
Many years ago I used to write "variable_", but then I changed to "_variable" because it is easier to identify private stuff writing _ and using autocomplete. This is the reason why there exist variables_ and _variables.

I would like to change all of them to _variable.

**Pull request merged**
